lib/terminus.js
lib/terminus.spec.js

Addresses https://github.com/godaddy/terminus/issues/1

fix(error-code): the process exits with the code derived from the signal

---

README.md
index.js
lib/standalone-tests/terminus.onshutdown.js
lib/standalone-tests/terminus.onsigterm.js
lib/terminus.js
lib/terminus.spec.js

moved files to strict mode and a couple writing nits.

minor cleanup

---

package.json
typings/express.test.ts
typings/index.d.ts
typings/index.test.ts
typings/koa.test.ts

Implements https://github.com/godaddy/terminus/issues/2

Added typings

---

example/postgres/index.js

Hi @gergelyke ,
This PR includes directly example to health check postgres database.
Regards,
Łukasz

[feat] Add db health check

---

example/mongo/Dockerfile
example/mongo/index.js
example/mongo/package-lock.json
example/mongo/package.json

Hi,
Thus is PR with mongo db example (#18 ).
Regards,
Łukasz

[feat] Add mongodb example

---

lib/terminus.js
package-lock.json

Issue #39 
I wasn't able to do exactly as the enhancement says, but I did set the defaults and destructed the object for its reuse in the helper functions. This does make it a bit more readable.

[init] inital commit for #39

---

example/cassandra/Dockerfile
example/cassandra/README.md
example/cassandra/index.js
example/cassandra/package-lock.json
example/cassandra/package.json

Hi @gergelyke ,
I finally made this PR with Cassandra example. Sorry for taking it so long.

[feat] Add cassandra example

---

.travis.yml

Greenkeepeer needs node version 8.3 or higher

fix(travis): release under node version 8

---

README.md
lib/terminus.js
lib/terminus.spec.js

this addresses #64 
/cc @gergelyke

include an info response in the healthcheck endpoint

---

lib/terminus.js
lib/terminus.spec.js

Add Content-Type header to JSON responses

---

README.md
example/cassandra/index.js
index.js
index.spec.js
lib/standalone-tests/terminus.multiserver.js
lib/standalone-tests/terminus.onmultiple.js
lib/standalone-tests/terminus.onshutdown.multiple.js
lib/standalone-tests/terminus.onshutdown.sigint.js
lib/standalone-tests/terminus.onshutdown.sigterm.js
lib/standalone-tests/terminus.onshutdown.sigusr2.js
lib/standalone-tests/terminus.onsigint.js
lib/standalone-tests/terminus.onsignal.fail.js
lib/standalone-tests/terminus.onsigterm.js
lib/standalone-tests/terminus.onsigusr2.js
lib/terminus-error.js
lib/terminus-error.spec.js
lib/terminus.js
lib/terminus.spec.js
package-lock.json
package.json

feat(error): custom message

---

typings/express.test.ts
typings/index.d.ts
typings/index.test.ts
typings/koa.test.ts

As discussed in #70 .
In addition, exposes interfaces to fix issue #75.
Thanks to this PR, you can have better intellisense support like:
```TypeScript
import { TerminusOptions } from "@godaddy/terminus";
const options: TerminusOptions = {
healthChecks: {
"/healthcheck": healthcheck
},
timeout: 1000,
onSignal,
onShutdown,
logger: console.log
};
```
Thanks to the `TerminusOptions` interface you exactly know which options are required / available.

Update typings for 3.0.0 release

---

lib/terminus.js
lib/terminus.spec.js

Closes https://github.com/godaddy/terminus/issues/91, in a non-breaking manner

fix(status): make it consistent

---

lib/terminus.js
lib/terminus.spec.js
package-lock.json

Current implementation will break the implementation.

fix(routes): option to make route matching case insensitive #124

---

typings/index.d.ts
typings/index.test.ts

feat(ts): added verbatim options

---

README.md

This helped us use this library with our own custom logging tool correctly and improves documentation

Update Logger documentation on ReadMe

---

.travis.yml

Remove greenhouse as it no longer exists. Causing latest builds to not publish via travis

chore(release): remove greenkeeper

---

example/oracle/.gitignore
example/oracle/index.js
example/oracle/package.json

I am a developer at Oracle Document Database Team; I came across this project recently, and wish to contribute an Oracle example.

Add example for Oracle Database

---

example/oracle/index.js
lib/terminus.js
lib/terminus.spec.js
package-lock.json
package.json

Remove unnecessary package as we can use native promisify. Also switched ot using `Promis.allSettled` for each of the processes in `cleanup`

feat(promisify): use native promisify and remove es6-promisify

---

.travis.yml

@rxmarbles i think this should solve the release issue

chore(ci): travis versions

---

example/mongoose/package.json

Updated mongoose package version in dependencies.

[Fix]  Upgrade mongoose package version in example directory

---

typings/index.d.ts

fix: fix typing 

---

README.md
lib/standalone-tests/terminus.onsignal.nofail.js
lib/terminus.js
lib/terminus.spec.js

Feature: Expose an internal state to health checks

---

README.md
lib/terminus.js
lib/terminus.spec.js
package-lock.json
typings/index.d.ts

Custom status

---

typings/index.d.ts

This is just a small fix to the typings so it emits the `state` option for `HealthCheck`

Add TerminusState type and update HealthCheck function type
